name: tv_randshow
description: App to pick a random TV show episode

version: 2.5.1+37

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  dio: ^5.9.0
  easy_localization: ^3.0.8
  file_saver: ^0.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7
  flutter_riverpod: ^2.6.1
  get_it: ^9.1.0
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  in_app_review: ^2.0.11
  injectable: ^2.6.0
  json_annotation: ^4.9.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  rive: ^0.14.2
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  stack_trace: ^1.12.1
  theme_provider: ^0.6.0
  unicons: ^3.0.0
  url_launcher: ^6.3.2
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.10.4
  faker: ^2.2.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.10.0
  injectable_generator: ^2.9.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.10.0
  mockito: ^5.4.6

flutter_native_splash:
  image: assets/img/icon_launcher.png
  color: "E40505"
  ios: false
  fullscreen: true

flutter_icons:
  android: "ic_launcher"
  adaptive_icon_foreground: "assets/img/icon_launcher_foreground.png"
  adaptive_icon_background: "#E40505"
  ios: false
  image_path: "assets/img/icon_launcher.png"

flutter:
  default-flavor: prod
  assets:
    - assets/i18n/
    - assets/markdown/
    - assets/img/no_image.webp
    - assets/img/tmdb.png
    - assets/img/loading.riv
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito-regular.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
