name: tv_randshow
description: App to pick a random TV show episode

version: 2.1.0+28

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cached_network_image: 3.3.1
  collection: 1.18.0
  dio: 5.4.0
  file_saver: 0.2.9
  flare_flutter: 3.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: 0.6.18+3
  flutter_riverpod: 2.4.9
  flutter_translate: 4.0.4
  get_it: 7.6.6
  hive: 2.2.3
  hive_flutter: 1.1.0
  in_app_review: 2.0.8
  injectable: 2.3.2
  json_annotation: 4.8.1
  package_info_plus: 5.0.1
  path: 1.8.3
  path_provider: 2.1.1
  shared_preferences: 2.2.2
  sqflite: 2.3.0
  stack_trace: 1.11.1
  theme_provider: 0.6.0
  unicons: 2.1.1
  url_launcher: 6.2.2

dev_dependencies:
  build_runner: 2.4.7
  faker: 2.1.0
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.1
  injectable_generator: 2.4.1
  integration_test:
    sdk: flutter
  json_serializable: 6.7.1
  mockito: 5.4.4

flutter_native_splash:
  image: assets/img/icon_launcher.png
  color: "E40505"
  ios: false
  fullscreen: true

flutter_icons:
  android: "ic_launcher"
  adaptive_icon_foreground: "assets/img/icon_launcher_foreground.png"
  adaptive_icon_background: "#E40505"
  ios: false
  image_path: "assets/img/icon_launcher.png"

flutter:
  assets:
    - assets/i18n/
    - assets/markdown/
    - assets/img/no_image.webp
    - assets/img/tmdb.png
    - assets/img/loading.flr
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito-regular.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
