name: tv_randshow
description: App to pick a random TV show episode

version: 1.4.1+12

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^2.3.2+1
  dio: ^3.0.10
  flare_flutter: ^2.0.6
  flutter_markdown: ^0.5.1
  flutter_pagewise: ^1.2.3
  flutter_translate: ^1.6.0
  get_it: ^4.0.2
  injectable: ^1.0.5
  json_annotation: ^3.1.0
  launch_review: ^2.0.0
  package_info_plus: ^0.5.0
  path_provider: ^1.6.18
  persist_theme: ^1.7.0
  provider: ^4.3.2+2
  sqflite: ^1.3.1+1
  stacked: ^1.7.6
  uni_links: ^0.4.0
  unicons: ^1.0.0+5
  url_launcher: ^5.7.2
  url_launcher_web: ^0.1.4+1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  build_runner: ^1.9.0
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9
  injectable_generator: ^1.0.4
  json_serializable: ^3.2.0
  mockito: ^4.1.3
  test: ^1.15.7

flutter_native_splash:
  image: assets/img/icon_launcher.png
  color: "E40505"

flutter_icons:
  android: "ic_launcher"
  adaptive_icon_foreground: "assets/img/icon_launcher_foreground.png"
  adaptive_icon_background: "#E40505"
  ios: false
  image_path: "assets/img/icon_launcher.png"

flutter:
  assets:
    - assets/i18n/
    - assets/markdown/
    - assets/img/no_image.webp
    - assets/img/loading.flr
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito-regular.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
