name: tv_randshow
description: App to pick a random TV show episode

version: 1.6.0+17

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^2.5.1
  dio: ^4.0.0-prev3
  file_saver: ^0.0.6
  flare_flutter: ^2.0.6
  flutter_markdown: ^0.5.1
  flutter_pagewise: ^1.2.3
  flutter_translate: ^2.0.0
  get_it: ^6.0.0
  in_app_review: ^2.0.1
  injectable: ^1.2.2
  json_annotation: ^3.1.1
  package_info_plus: ^1.0.0
  path_provider: ^2.0.1
  permission_handler: ^6.1.1
  persist_theme: ^1.7.0
  provider: ^4.3.2+2
  sqflite: ^2.0.0+3
  stacked: ^1.7.6
  uni_links: ^0.4.0
  unicons: ^1.0.2
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  build_runner: ^1.9.0
  faker: ^2.0.0
  flutter_launcher_icons: ^0.8.1
  injectable_generator: ^1.0.4
  json_serializable: ^3.5.1
  mockito: ^4.1.3
  test: ^1.15.8

dependency_overrides:
  crypto: 2.1.5 

flutter_native_splash:
  image: assets/img/icon_launcher.png
  color: "E40505"
  ios: false
  fullscreen: true

flutter_icons:
  android: "ic_launcher"
  adaptive_icon_foreground: "assets/img/icon_launcher_foreground.png"
  adaptive_icon_background: "#E40505"
  ios: false
  image_path: "assets/img/icon_launcher.png"

flutter:
  assets:
    - assets/i18n/
    - assets/markdown/
    - assets/img/no_image.webp
    - assets/img/loading.flr
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito-regular.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
